language: node_js
node_js:
- 10

sudo: required

script:
- ssh-keyscan -H 95.163.248.216 >> ~/.ssh/known_hosts
- scp -i ./jsdaddy_id_rsa.pem ./index.html ubuntu@95.163.248.216:/home/ubuntu/www/index.html
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_e1982a93ff2e_key -iv $encrypted_e1982a93ff2e_iv
  -in jsdaddy_id_rsa.pem.enc -out ./jsdaddy_id_rsa.pem -d
